/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.conexaoBD;

/**
 *
 * @author taysy
 */
public class TelaPrincipal extends javax.swing.JFrame {

    //conexaoBD conectar = new conexaoBD();
    
    public TelaPrincipal() {
        initComponents();
        //conectar.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoBemVindo = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadVeterinario = new javax.swing.JButton();
        jButtonCadAnimal = new javax.swing.JButton();
        jButtonCdCliente = new javax.swing.JButton();
        jPanelAgendamento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAgendamentos = new javax.swing.JButton();
        jButtonSairCad = new javax.swing.JButton();
        jLabelPlanoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadVeterinario = new javax.swing.JMenuItem();
        jMenuItemAnimais = new javax.swing.JMenuItem();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabelFundoBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-bemVindo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCadastro.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastros :");
        jPanelCadastro.add(jLabel1);
        jLabel1.setBounds(10, 20, 80, 20);

        jButtonCadVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadMedicos.png"))); // NOI18N
        jButtonCadVeterinario.setToolTipText("Veterinarios");
        jButtonCadVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadVeterinarioActionPerformed(evt);
            }
        });
        jPanelCadastro.add(jButtonCadVeterinario);
        jButtonCadVeterinario.setBounds(10, 60, 90, 110);

        jButtonCadAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadAnimal.png"))); // NOI18N
        jButtonCadAnimal.setToolTipText("Animal");
        jButtonCadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAnimalActionPerformed(evt);
            }
        });
        jPanelCadastro.add(jButtonCadAnimal);
        jButtonCadAnimal.setBounds(110, 60, 80, 110);

        jButtonCdCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadPacientes.png"))); // NOI18N
        jButtonCdCliente.setToolTipText("Cliente");
        jButtonCdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCdClienteActionPerformed(evt);
            }
        });
        jPanelCadastro.add(jButtonCdCliente);
        jButtonCdCliente.setBounds(200, 60, 80, 110);

        jPanelAgendamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelAgendamento.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Agendar:");
        jPanelAgendamento.add(jLabel2);
        jLabel2.setBounds(10, 20, 100, 30);

        jButtonAgendamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda.png"))); // NOI18N
        jButtonAgendamentos.setToolTipText("Agenda");
        jButtonAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendamentosActionPerformed(evt);
            }
        });
        jPanelAgendamento.add(jButtonAgendamentos);
        jButtonAgendamentos.setBounds(30, 60, 90, 110);

        jPanelCadastro.add(jPanelAgendamento);
        jPanelAgendamento.setBounds(290, 0, 200, 190);

        jInternalFrameBemVindo.getContentPane().add(jPanelCadastro);
        jPanelCadastro.setBounds(0, 50, 490, 190);

        jButtonSairCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jButtonSairCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonSairCad);
        jButtonSairCad.setBounds(430, 0, 50, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 50, 500, 270);

        jLabelPlanoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelPlanoTelaPrincipal);
        jLabelPlanoTelaPrincipal.setBounds(0, 0, 500, 320);

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadVeterinario.setText("Veterinarios");
        jMenuItemCadVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadVeterinarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadVeterinario);

        jMenuItemAnimais.setText("Animais");
        jMenuItemAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnimaisActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemAnimais);

        jMenuItemCadCliente.setText("Cliente");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadCliente);

        jMenuItemUsuarios.setText("Usuários");
        jMenuCadastros.add(jMenuItemUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatorios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemBemVindo.setText("Bem-Vindo");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(515, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadActionPerformed
       jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonSairCadActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        //conectar.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jMenuItemCadVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadVeterinarioActionPerformed
       TelaCadastroVeterinario veterinario = new TelaCadastroVeterinario();
       veterinario.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadVeterinarioActionPerformed

    private void jButtonCadVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadVeterinarioActionPerformed
       TelaCadastroVeterinario veterinario = new TelaCadastroVeterinario();
       veterinario.setVisible(true);
    }//GEN-LAST:event_jButtonCadVeterinarioActionPerformed

    private void jButtonCdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCdClienteActionPerformed
       TelaCadastroCliente cliente = new TelaCadastroCliente();
       cliente.setVisible(true);
    }//GEN-LAST:event_jButtonCdClienteActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        TelaCadastroCliente cliente = new TelaCadastroCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jButtonCadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAnimalActionPerformed
        TelaCadastraAnimal animal = new TelaCadastraAnimal();
        animal.setVisible(true);
    }//GEN-LAST:event_jButtonCadAnimalActionPerformed

    private void jMenuItemAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnimaisActionPerformed
        TelaCadastraAnimal animal = new TelaCadastraAnimal();
        animal.setVisible(true);
    }//GEN-LAST:event_jMenuItemAnimaisActionPerformed

    private void jButtonAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendamentosActionPerformed
       TelaCadastraConsulta consulta = new TelaCadastraConsulta();
       consulta.setVisible(true);
    }//GEN-LAST:event_jButtonAgendamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendamentos;
    private javax.swing.JButton jButtonCadAnimal;
    private javax.swing.JButton jButtonCadVeterinario;
    private javax.swing.JButton jButtonCdCliente;
    private javax.swing.JButton jButtonSairCad;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundoBemVindo;
    private javax.swing.JLabel jLabelPlanoTelaPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemAnimais;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadVeterinario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelAgendamento;
    private javax.swing.JPanel jPanelCadastro;
    // End of variables declaration//GEN-END:variables
}
