/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CadastraCliente;
import controle.conexaoBD;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author taysy
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    Cliente cl = new Cliente();
    CadastraCliente cont = new CadastraCliente();
    conexaoBD conex = new conexaoBD();
    int flag =0;
    
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIdCliente = new javax.swing.JLabel();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jLabelNomeCliente = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jLabelCpfClienet = new javax.swing.JLabel();
        jTextFieldCpfClienet = new javax.swing.JTextField();
        jLabelRgCliente = new javax.swing.JLabel();
        jTextFieldRgCliente = new javax.swing.JTextField();
        jLabelTelefoneClienet = new javax.swing.JLabel();
        jTextFieldTelefoneCliente = new javax.swing.JTextField();
        jLabelIdadeCliente = new javax.swing.JLabel();
        jTextFieldIdadeCliente = new javax.swing.JTextField();
        jLabelEnderecoCliente = new javax.swing.JLabel();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jLabelCidadeCliente = new javax.swing.JLabel();
        jTextFieldCidadeCliente = new javax.swing.JTextField();
        jLabelEstadoCliente = new javax.swing.JLabel();
        jTextFieldEstadoCliente = new javax.swing.JTextField();
        jButtonSalaver = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabelIdCliente.setText("Codigo:");
        jPanel1.add(jLabelIdCliente);
        jLabelIdCliente.setBounds(50, 20, 50, 14);

        jTextFieldIdCliente.setEnabled(false);
        jPanel1.add(jTextFieldIdCliente);
        jTextFieldIdCliente.setBounds(90, 10, 80, 30);

        jLabelNomeCliente.setText("Nome:");
        jPanel1.add(jLabelNomeCliente);
        jLabelNomeCliente.setBounds(50, 70, 50, 14);

        jTextFieldNomeCliente.setEnabled(false);
        jPanel1.add(jTextFieldNomeCliente);
        jTextFieldNomeCliente.setBounds(90, 60, 350, 30);

        jLabelCpfClienet.setText("CPF:");
        jPanel1.add(jLabelCpfClienet);
        jLabelCpfClienet.setBounds(50, 120, 30, 14);

        jTextFieldCpfClienet.setEnabled(false);
        jPanel1.add(jTextFieldCpfClienet);
        jTextFieldCpfClienet.setBounds(90, 110, 140, 30);

        jLabelRgCliente.setText("RG:");
        jPanel1.add(jLabelRgCliente);
        jLabelRgCliente.setBounds(280, 120, 30, 14);

        jTextFieldRgCliente.setEnabled(false);
        jPanel1.add(jTextFieldRgCliente);
        jTextFieldRgCliente.setBounds(310, 110, 130, 30);

        jLabelTelefoneClienet.setText("Telefone:");
        jPanel1.add(jLabelTelefoneClienet);
        jLabelTelefoneClienet.setBounds(30, 170, 60, 14);

        jTextFieldTelefoneCliente.setEnabled(false);
        jPanel1.add(jTextFieldTelefoneCliente);
        jTextFieldTelefoneCliente.setBounds(90, 160, 140, 30);

        jLabelIdadeCliente.setText("Idade:");
        jPanel1.add(jLabelIdadeCliente);
        jLabelIdadeCliente.setBounds(270, 170, 50, 14);

        jTextFieldIdadeCliente.setEnabled(false);
        jPanel1.add(jTextFieldIdadeCliente);
        jTextFieldIdadeCliente.setBounds(310, 160, 130, 30);

        jLabelEnderecoCliente.setText("Endereço:");
        jPanel1.add(jLabelEnderecoCliente);
        jLabelEnderecoCliente.setBounds(30, 210, 60, 20);

        jTextFieldEnderecoCliente.setEnabled(false);
        jPanel1.add(jTextFieldEnderecoCliente);
        jTextFieldEnderecoCliente.setBounds(90, 210, 140, 30);

        jLabelCidadeCliente.setText("Cidade:");
        jPanel1.add(jLabelCidadeCliente);
        jLabelCidadeCliente.setBounds(270, 220, 50, 14);

        jTextFieldCidadeCliente.setEnabled(false);
        jPanel1.add(jTextFieldCidadeCliente);
        jTextFieldCidadeCliente.setBounds(310, 210, 130, 30);

        jLabelEstadoCliente.setText("Estado:");
        jPanel1.add(jLabelEstadoCliente);
        jLabelEstadoCliente.setBounds(40, 270, 50, 14);

        jTextFieldEstadoCliente.setEnabled(false);
        jPanel1.add(jTextFieldEstadoCliente);
        jTextFieldEstadoCliente.setBounds(90, 260, 60, 30);

        jButtonSalaver.setText("Salvar");
        jButtonSalaver.setEnabled(false);
        jButtonSalaver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalaverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalaver);
        jButtonSalaver.setBounds(60, 350, 63, 23);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNovo);
        jButtonNovo.setBounds(150, 350, 57, 23);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jPanel1.add(jButtonCancelar);
        jButtonCancelar.setBounds(240, 350, 80, 23);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(350, 350, 61, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(430, 350, 70, 23);
        jPanel1.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(90, 300, 210, 30);

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisa);
        jButtonPesquisa.setBounds(310, 300, 100, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 580, 410);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 120, 17);

        setSize(new java.awt.Dimension(609, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalaverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalaverActionPerformed
      if (flag == 1){
       cl.setNome(jTextFieldNomeCliente.getText());
       cl.setCpf(jTextFieldCpfClienet.getText());
       cl.setRg(jTextFieldRgCliente.getText());
       cl.setTelefone(jTextFieldTelefoneCliente.getText());
       cl.setIdade(Integer.parseInt(jTextFieldIdadeCliente.getText()));
       cl.setEndereco(jTextFieldEnderecoCliente.getText());
       cl.setCidade(jTextFieldCidadeCliente.getText());
       cl.setEstado(jTextFieldEstadoCliente.getText());
       cont.Salvar(cl);
       
        jTextFieldNomeCliente.setText("");
        jTextFieldCpfClienet.setText("");
        jTextFieldRgCliente.setText("");
        jTextFieldTelefoneCliente.setText("");
        jTextFieldIdadeCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jTextFieldEstadoCliente.setText("");
       
       
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldCpfClienet.setEnabled(false);
        jTextFieldRgCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jTextFieldIdadeCliente.setEnabled(false);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldCidadeCliente.setEnabled(false);
        jTextFieldEstadoCliente.setEnabled(false);
        jButtonSalaver.setEnabled(false);
        jButtonCancelar.setEnabled(false);
       
      }else{
       cl.setCod(Integer.parseInt(jTextFieldIdCliente.getText()));
       cl.setNome(jTextFieldNomeCliente.getText());
       cl.setCpf(jTextFieldCpfClienet.getText());
       cl.setRg(jTextFieldRgCliente.getText());
       cl.setTelefone(jTextFieldTelefoneCliente.getText());
       cl.setIdade(Integer.parseInt(jTextFieldIdadeCliente.getText()));
       cl.setEndereco(jTextFieldEnderecoCliente.getText());
       cl.setCidade(jTextFieldCidadeCliente.getText());
       cl.setEstado(jTextFieldEstadoCliente.getText());
       cont.Editar(cl);
       
       jTextFieldNomeCliente.setText("");
        jTextFieldCpfClienet.setText("");
        jTextFieldRgCliente.setText("");
        jTextFieldTelefoneCliente.setText("");
        jTextFieldIdadeCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jTextFieldEstadoCliente.setText("");
        
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldCpfClienet.setEnabled(false);
        jTextFieldRgCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jTextFieldIdadeCliente.setEnabled(false);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldCidadeCliente.setEnabled(false);
        jTextFieldEstadoCliente.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonSalaver.setEnabled(false);
      }
    }//GEN-LAST:event_jButtonSalaverActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
       cl.setPesquisa(jTextFieldPesquisa.getText());
       Cliente clp = cont.pesquisaCliente(cl);
       
       jTextFieldIdCliente.setText(String.valueOf(clp.getCod()));
       jTextFieldNomeCliente.setText(clp.getNome());
       jTextFieldCpfClienet.setText(clp.getCpf());
       jTextFieldRgCliente.setText(clp.getRg());
       jTextFieldTelefoneCliente.setText(clp.getTelefone());
       jTextFieldIdadeCliente.setText(String.valueOf(clp.getIdade()));
       jTextFieldEnderecoCliente.setText(clp.getEndereco());
       jTextFieldCidadeCliente.setText(clp.getCidade());
       jTextFieldEstadoCliente.setText(clp.getEstado());
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldCpfClienet.setEnabled(true);
        jTextFieldRgCliente.setEnabled(true);
        jTextFieldTelefoneCliente.setEnabled(true);
        jTextFieldIdadeCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(true);
        jTextFieldCidadeCliente.setEnabled(true);
        jTextFieldEstadoCliente.setEnabled(true);
        jButtonSalaver.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldCpfClienet.setEnabled(true);
        jTextFieldRgCliente.setEnabled(true);
        jTextFieldTelefoneCliente.setEnabled(true);
        jTextFieldIdadeCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(true);
        jTextFieldCidadeCliente.setEnabled(true);
        jTextFieldEstadoCliente.setEnabled(true);
        jButtonSalaver.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       int reposta = 0;
       reposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir esse cliente?");
       if (reposta == JOptionPane.YES_OPTION) {
           cl.setCod(Integer.parseInt(jTextFieldIdCliente.getText()));
           cont.Excluir(cl);
           
        jTextFieldNomeCliente.setText("");
        jTextFieldCpfClienet.setText("");
        jTextFieldRgCliente.setText("");
        jTextFieldTelefoneCliente.setText("");
        jTextFieldIdadeCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jTextFieldEstadoCliente.setText("");
        
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldCpfClienet.setEnabled(false);
        jTextFieldRgCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jTextFieldIdadeCliente.setEnabled(false);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldCidadeCliente.setEnabled(false);
        jTextFieldEstadoCliente.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonSalaver.setEnabled(false);
       }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalaver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCidadeCliente;
    private javax.swing.JLabel jLabelCpfClienet;
    private javax.swing.JLabel jLabelEnderecoCliente;
    private javax.swing.JLabel jLabelEstadoCliente;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelIdadeCliente;
    private javax.swing.JLabel jLabelNomeCliente;
    private javax.swing.JLabel jLabelRgCliente;
    private javax.swing.JLabel jLabelTelefoneClienet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCidadeCliente;
    private javax.swing.JTextField jTextFieldCpfClienet;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldEstadoCliente;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldIdadeCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRgCliente;
    private javax.swing.JTextField jTextFieldTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
