/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CadastraConsulta;
import controle.conexaoBD;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Consulta;

/**
 *
 * @author taysy
 */
public class TelaCadastraConsulta extends javax.swing.JFrame {

    conexaoBD conex = new conexaoBD();
    Consulta c = new Consulta();
    CadastraConsulta cont = new CadastraConsulta();
    int flag =0;
    
    public TelaCadastraConsulta() {
        initComponents();
        //carragarAnimal();
        preencherDono();
        carregarVeterinario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAnimalConsulta = new javax.swing.JLabel();
        jLabelDonoConsulta = new javax.swing.JLabel();
        jComboBoxDonoConsulta = new javax.swing.JComboBox<>();
        jLabelVetrinario = new javax.swing.JLabel();
        jComboBoxVeterinarioConsulta = new javax.swing.JComboBox<>();
        jFormattedTextFieldDataVeterinario = new javax.swing.JFormattedTextField();
        jLabelData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jFormattedTextFieldHorarioConsulta = new javax.swing.JFormattedTextField();
        jLabelIdConsulta = new javax.swing.JLabel();
        jTextFieldIdConsulta = new javax.swing.JTextField();
        jTextFieldPesquisaConsulta = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jTextFieldAnimalConsulat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelAnimalConsulta.setText("Animal:");

        jLabelDonoConsulta.setText("Dono:");

        jComboBoxDonoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDonoConsulta.setEnabled(false);

        jLabelVetrinario.setText("Veterinario:");

        jComboBoxVeterinarioConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxVeterinarioConsulta.setEnabled(false);

        try {
            jFormattedTextFieldDataVeterinario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataVeterinario.setEnabled(false);

        jLabelData.setText("Data:");

        jLabel2.setText("Horário:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldHorarioConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldHorarioConsulta.setEnabled(false);

        jLabelIdConsulta.setText("Codigo: ");

        jTextFieldIdConsulta.setEnabled(false);

        jTextFieldPesquisaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaConsultaActionPerformed(evt);
            }
        });

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jTextFieldAnimalConsulat.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelVetrinario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelAnimalConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelIdConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxVeterinarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldHorarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAnimalConsulat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabelDonoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelData, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldDataVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxDonoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextFieldIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(16, 16, 16)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIdConsulta))
                    .addComponent(jTextFieldIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDonoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDonoConsulta)
                    .addComponent(jLabelAnimalConsulta)
                    .addComponent(jTextFieldAnimalConsulat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxVeterinarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVetrinario)
                    .addComponent(jFormattedTextFieldDataVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldHorarioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButtonPesquisa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addGap(70, 70, 70))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 540, 360);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastra Consulta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 120, 17);

        setSize(new java.awt.Dimension(573, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //public void carragarAnimal(){
      //  conex.conexao();
        
       // conex.executarSql("select *from animais order by nome_animal");
       // try {
        //    conex.rs.first();
          //  jComboBoxAnimalConsulta.removeAllItems();
          //  do{
       //       jComboBoxAnimalConsulta.addItem(conex.rs.getString("nome_animal"));
       //     }while(conex.rs.next());
     //   } catch (SQLException ex) {
     //       JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Dono"+ex);
      //  }
      //  conex.desconecta();
    //}
    
    public void preencherDono(){
        conex.conexao();
        
        conex.executarSql("select *from clientes order by nome_cliente");
        try {
            conex.rs.first();
            jComboBoxDonoConsulta.removeAllItems();
            do{
              jComboBoxDonoConsulta.addItem(conex.rs.getString("nome_cliente"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Dono"+ex);
        }
        conex.desconecta();
        
    }
    
    public void carregarVeterinario(){
        conex.conexao();
        
        conex.executarSql("select *from veterinarios order by nome_veterinario");
        try {
            conex.rs.first();
            jComboBoxVeterinarioConsulta.removeAllItems();
            do{
              jComboBoxVeterinarioConsulta.addItem(conex.rs.getString("nome_veterinario"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Dono"+ex);
        }
        conex.desconecta();
    }
    
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if (flag == 1) {
       c.setAnimal(jTextFieldAnimalConsulat.getText());
       c.setDono((String) jComboBoxDonoConsulta.getSelectedItem());
       c.setVeterinario((String) jComboBoxVeterinarioConsulta.getSelectedItem());
       c.setData(jFormattedTextFieldDataVeterinario.getText());
       c.setHorario(jFormattedTextFieldHorarioConsulta.getText());
       cont.Salvar(c);
       
       jTextFieldIdConsulta.setText("");
       jTextFieldAnimalConsulat.setText("");
       jComboBoxDonoConsulta.setToolTipText("");
       jComboBoxVeterinarioConsulta.setToolTipText("");
       jFormattedTextFieldDataVeterinario.setText("");
       jFormattedTextFieldHorarioConsulta.setText("");
       
       jTextFieldAnimalConsulat.setEnabled(false);
       jComboBoxDonoConsulta.setEnabled(false);
       jComboBoxVeterinarioConsulta.setEnabled(false);
       jFormattedTextFieldDataVeterinario.setEnabled(false);
       jFormattedTextFieldHorarioConsulta.setEnabled(false);
       jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
      }else{
       
       c.setCod(Integer.parseInt(jTextFieldIdConsulta.getText()));
       c.setAnimal(jTextFieldAnimalConsulat.getText());
       c.setDono((String) jComboBoxDonoConsulta.getSelectedItem());
       c.setVeterinario((String) jComboBoxVeterinarioConsulta.getSelectedItem());
       c.setData(jFormattedTextFieldDataVeterinario.getText());
       c.setHorario(jFormattedTextFieldHorarioConsulta.getText());
       cont.Editar(c);
       
       jTextFieldIdConsulta.setText("");
       jTextFieldAnimalConsulat.setText("");
       jComboBoxDonoConsulta.setToolTipText("");
       jComboBoxVeterinarioConsulta.setToolTipText("");
       jFormattedTextFieldDataVeterinario.setText("");
       jFormattedTextFieldHorarioConsulta.setText("");
       
       jTextFieldAnimalConsulat.setEnabled(false);
       jComboBoxDonoConsulta.setEnabled(false);
       jComboBoxVeterinarioConsulta.setEnabled(false);
       jFormattedTextFieldDataVeterinario.setEnabled(false);
       jFormattedTextFieldHorarioConsulta.setEnabled(false);
       jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
          
      }
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldPesquisaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaConsultaActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
       c.setPesquisa(jTextFieldAnimalConsulat.getText());
       Consulta cp = cont.pesquisarConsulta(c);
       
       jTextFieldIdConsulta.setText(String.valueOf(cp.getCod()));
       jTextFieldAnimalConsulat.setText(cp.getAnimal());
       jComboBoxDonoConsulta.setToolTipText(cp.getDono());
       jComboBoxVeterinarioConsulta.setToolTipText(cp.getVeterinario());
       jFormattedTextFieldDataVeterinario.setText(cp.getData());
       jFormattedTextFieldHorarioConsulta.setText(cp.getHorario());
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
       jTextFieldAnimalConsulat.setEnabled(true);
       jComboBoxDonoConsulta.setEnabled(true);
       jComboBoxVeterinarioConsulta.setEnabled(true);
       jFormattedTextFieldDataVeterinario.setEnabled(true);
       jFormattedTextFieldHorarioConsulta.setEnabled(true);
       jButtonSalvar.setEnabled(true);
       jButtonCancelar.setEnabled(true);
       jButtonEditar.setEnabled(false);
       jButtonNovo.setEnabled(false);
       jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
       flag = 1;
       jTextFieldAnimalConsulat.setEnabled(true);
       jComboBoxDonoConsulta.setEnabled(true);
       jComboBoxVeterinarioConsulta.setEnabled(true);
       jFormattedTextFieldDataVeterinario.setEnabled(true);
       jFormattedTextFieldHorarioConsulta.setEnabled(true);
       jButtonSalvar.setEnabled(true);
       jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            c.setCod(Integer.parseInt(jTextFieldIdConsulta.getText()));
            cont.Excluir(c);
            
       jTextFieldIdConsulta.setText("");
       jTextFieldAnimalConsulat.setText("");
       jComboBoxDonoConsulta.setToolTipText("");
       jComboBoxVeterinarioConsulta.setToolTipText("");
       jFormattedTextFieldDataVeterinario.setText("");
       jFormattedTextFieldHorarioConsulta.setText("");
       
       jTextFieldAnimalConsulat.setEnabled(false);
       jComboBoxDonoConsulta.setEnabled(false);
       jComboBoxVeterinarioConsulta.setEnabled(false);
       jFormattedTextFieldDataVeterinario.setEnabled(false);
       jFormattedTextFieldHorarioConsulta.setEnabled(false);
       jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       jTextFieldAnimalConsulat.setEnabled(!true);
       jComboBoxDonoConsulta.setEnabled(!true);
       jComboBoxVeterinarioConsulta.setEnabled(!true);
       jFormattedTextFieldDataVeterinario.setEnabled(!true);
       jFormattedTextFieldHorarioConsulta.setEnabled(!true);
       jButtonSalvar.setEnabled(!true);
       jButtonCancelar.setEnabled(!true);
       jButtonNovo.setEnabled(true);
       jButtonEditar.setEnabled(false);
       jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastraConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxDonoConsulta;
    private javax.swing.JComboBox<String> jComboBoxVeterinarioConsulta;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataVeterinario;
    private javax.swing.JFormattedTextField jFormattedTextFieldHorarioConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAnimalConsulta;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDonoConsulta;
    private javax.swing.JLabel jLabelIdConsulta;
    private javax.swing.JLabel jLabelVetrinario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAnimalConsulat;
    private javax.swing.JTextField jTextFieldIdConsulta;
    private javax.swing.JTextField jTextFieldPesquisaConsulta;
    // End of variables declaration//GEN-END:variables
}
