/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CadastraAnimal;
import controle.conexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Animal;

/**
 *
 * @author taysy
 */
public class TelaCadastraAnimal extends javax.swing.JFrame {
    Animal a = new Animal();
    CadastraAnimal cont = new CadastraAnimal();
    conexaoBD conex = new conexaoBD();
    int flag =0;
    
    public TelaCadastraAnimal() {
        initComponents();
        preencherDono();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelIdAnimal = new javax.swing.JLabel();
        jTextFieldIdAnimal = new javax.swing.JTextField();
        jLabelNomeAnimal = new javax.swing.JLabel();
        jTextFieldNomeAnimal = new javax.swing.JTextField();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldIdadeAnimal = new javax.swing.JTextField();
        jLabelSexoAnimal = new javax.swing.JLabel();
        jTextFieldSexoAnimal = new javax.swing.JTextField();
        jLabelRacaAnimal = new javax.swing.JLabel();
        jTextFieldRacaAnimal = new javax.swing.JTextField();
        jLabelEspecieAnimal = new javax.swing.JLabel();
        jTextFieldEspecieAnimal = new javax.swing.JTextField();
        jLabelDono = new javax.swing.JLabel();
        jComboBoxDonoAnimal = new javax.swing.JComboBox<>();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelIdAnimal.setText("Codigo:");

        jTextFieldIdAnimal.setEnabled(false);

        jLabelNomeAnimal.setText("Nome:");

        jTextFieldNomeAnimal.setEnabled(false);

        jLabelIdade.setText("Idade:");

        jTextFieldIdadeAnimal.setEnabled(false);

        jLabelSexoAnimal.setText("Sexo:");

        jTextFieldSexoAnimal.setEnabled(false);

        jLabelRacaAnimal.setText("Raça:");

        jTextFieldRacaAnimal.setEnabled(false);

        jLabelEspecieAnimal.setText("Espécie:");

        jTextFieldEspecieAnimal.setEnabled(false);

        jLabelDono.setText("Dono:");

        jComboBoxDonoAnimal.setEnabled(false);

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEspecieAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldSexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEspecieAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDono, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRacaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jLabelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldIdadeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(jTextFieldRacaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jComboBoxDonoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdAnimal)
                    .addComponent(jTextFieldIdAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNomeAnimal))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIdadeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelIdade)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexoAnimal)
                    .addComponent(jTextFieldSexoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRacaAnimal)
                    .addComponent(jTextFieldRacaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEspecieAnimal)
                    .addComponent(jTextFieldEspecieAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDono)
                    .addComponent(jComboBoxDonoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 564, 380);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastra Animal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 110, 17);

        setSize(new java.awt.Dimension(598, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void preencherDono(){
        conex.conexao();
        
        conex.executarSql("select *from clientes order by nome_cliente");
        try {
            conex.rs.first();
            jComboBoxDonoAnimal.removeAllItems();
            do{
              jComboBoxDonoAnimal.addItem(conex.rs.getString("nome_cliente"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher Dono"+ex);
        }
        conex.desconecta();
        
    }
    
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       int reposta = 0;
       reposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
       if(reposta == JOptionPane.YES_OPTION){
           a.setCod(Integer.parseInt(jTextFieldIdAnimal.getText()));
           cont.Excluir(a);
        
        jTextFieldIdAnimal.setText("");
        jTextFieldNomeAnimal.setText("");
        jTextFieldIdadeAnimal.setText("");
        jTextFieldSexoAnimal.setText("");
        jTextFieldRacaAnimal.setText("");
        jTextFieldEspecieAnimal.setText("");
        jComboBoxDonoAnimal.setToolTipText("");
           
        jTextFieldNomeAnimal.setEnabled(false);
        jTextFieldIdadeAnimal.setEnabled(false);
        jTextFieldSexoAnimal.setEnabled(false);
        jTextFieldRacaAnimal.setEnabled(false);
        jTextFieldEspecieAnimal.setEnabled(false);
        jComboBoxDonoAnimal.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
       }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if (flag==1) {
       a.setNome(jTextFieldNomeAnimal.getText());
       a.setIdade(Integer.parseInt(jTextFieldIdadeAnimal.getText()));
       a.setSexo(jTextFieldSexoAnimal.getText());
       a.setRaca(jTextFieldRacaAnimal.getText());
       a.setEspecie(jTextFieldEspecieAnimal.getText());
       a.setDono((String) jComboBoxDonoAnimal.getSelectedItem());
       cont.Salvar(a);
       
       jTextFieldIdAnimal.setText("");
        jTextFieldNomeAnimal.setText("");
        jTextFieldIdadeAnimal.setText("");
        jTextFieldSexoAnimal.setText("");
        jTextFieldRacaAnimal.setText("");
        jTextFieldEspecieAnimal.setText("");
        jComboBoxDonoAnimal.setToolTipText("");
        
        jTextFieldNomeAnimal.setEnabled(false);
        jTextFieldIdadeAnimal.setEnabled(false);
        jTextFieldSexoAnimal.setEnabled(false);
        jTextFieldRacaAnimal.setEnabled(false);
        jTextFieldEspecieAnimal.setEnabled(false);
        jComboBoxDonoAnimal.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
      }else{
       a.setCod(Integer.parseInt(jTextFieldIdAnimal.getText()));
       a.setNome(jTextFieldNomeAnimal.getText());
       a.setIdade(Integer.parseInt(jTextFieldIdadeAnimal.getText()));
       a.setSexo(jTextFieldSexoAnimal.getText());
       a.setRaca(jTextFieldRacaAnimal.getText());
       a.setEspecie(jTextFieldEspecieAnimal.getText());
       a.setDono((String) jComboBoxDonoAnimal.getSelectedItem());
       cont.Edita(a);
        
        jTextFieldIdAnimal.setText("");
        jTextFieldNomeAnimal.setText("");
        jTextFieldIdadeAnimal.setText("");
        jTextFieldSexoAnimal.setText("");
        jTextFieldRacaAnimal.setText("");
        jTextFieldEspecieAnimal.setText("");
        jComboBoxDonoAnimal.setToolTipText("");
        
        jTextFieldNomeAnimal.setEnabled(false);
        jTextFieldIdadeAnimal.setEnabled(false);
        jTextFieldSexoAnimal.setEnabled(false);
        jTextFieldRacaAnimal.setEnabled(false);
        jTextFieldEspecieAnimal.setEnabled(false);
        jComboBoxDonoAnimal.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
          
      }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
       a.setPesquisa(jTextFieldNomeAnimal.getText());
       Animal ap =cont.pesquisaAnimal(a);
       
       jTextFieldIdAnimal.setText(String.valueOf(ap.getCod()));
       jTextFieldNomeAnimal.setText(ap.getNome());
       jTextFieldIdadeAnimal.setText(String.valueOf(ap.getIdade()));
       jTextFieldSexoAnimal.setText(ap.getSexo());
       jTextFieldRacaAnimal.setText(ap.getRaca());
       jTextFieldEspecieAnimal.setText(ap.getEspecie());
       jComboBoxDonoAnimal.setToolTipText(ap.getDono());
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNomeAnimal.setEnabled(true);
        jTextFieldIdadeAnimal.setEnabled(true);
        jTextFieldSexoAnimal.setEnabled(true);
        jTextFieldRacaAnimal.setEnabled(true);
        jTextFieldEspecieAnimal.setEnabled(true);
        jComboBoxDonoAnimal.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomeAnimal.setEnabled(true);
        jTextFieldIdadeAnimal.setEnabled(true);
        jTextFieldSexoAnimal.setEnabled(true);
        jTextFieldRacaAnimal.setEnabled(true);
        jTextFieldEspecieAnimal.setEnabled(true);
        jComboBoxDonoAnimal.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNomeAnimal.setEnabled(!true);
        jTextFieldIdadeAnimal.setEnabled(!true);
        jTextFieldSexoAnimal.setEnabled(!true);
        jTextFieldRacaAnimal.setEnabled(!true);
        jTextFieldEspecieAnimal.setEnabled(!true);
        jComboBoxDonoAnimal.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastraAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastraAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxDonoAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDono;
    private javax.swing.JLabel jLabelEspecieAnimal;
    private javax.swing.JLabel jLabelIdAnimal;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelNomeAnimal;
    private javax.swing.JLabel jLabelRacaAnimal;
    private javax.swing.JLabel jLabelSexoAnimal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEspecieAnimal;
    private javax.swing.JTextField jTextFieldIdAnimal;
    private javax.swing.JTextField jTextFieldIdadeAnimal;
    private javax.swing.JTextField jTextFieldNomeAnimal;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldRacaAnimal;
    private javax.swing.JTextField jTextFieldSexoAnimal;
    // End of variables declaration//GEN-END:variables
}
