/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CadastroVeterinario;
import controle.conexaoBD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Veterinario;
import java.sql.*;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;
import modelo.Tabela;
import modelo.Tabela;

/**
 *
 * @author taysy
 */
public class TelaCadastroVeterinario extends javax.swing.JFrame {

    Veterinario vet = new Veterinario();
    CadastroVeterinario cont = new CadastroVeterinario();
    conexaoBD conex = new conexaoBD();
    int flag = 0;
    
    public TelaCadastroVeterinario() {
        initComponents();
        //preencherTabela("select *from veterinarios order by nome_veterinario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldNomeVet = new javax.swing.JTextField();
        jTextFieldRgVet = new javax.swing.JTextField();
        jTextFieldCpfVet = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmailVet = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldTelefoneVet = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldIdadeVet = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVeterinario = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisarVet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdVeterinario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNome.setText("Nome:");

        jLabelRg.setText("RG:");

        jLabelCpf.setText("CPF:");

        jTextFieldNomeVet.setEnabled(false);

        jTextFieldRgVet.setEnabled(false);

        jTextFieldCpfVet.setEnabled(false);

        jLabelEmail.setText("E-mail:");

        jTextFieldEmailVet.setEnabled(false);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelTelefone.setText("Telafone:");

        jTextFieldTelefoneVet.setEnabled(false);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelIdade.setText("Idade:");

        jTextFieldIdadeVet.setEnabled(false);

        jTableVeterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableVeterinario);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonPesquisarVet.setText("Pesquisar");
        jButtonPesquisarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarVetActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo:");

        jTextFieldIdVeterinario.setEnabled(false);
        jTextFieldIdVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdVeterinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelRg, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeVet)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldRgVet, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)
                                                .addComponent(jLabelTelefone)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldTelefoneVet)
                                            .addComponent(jTextFieldIdadeVet, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCpfVet, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldEmailVet, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jTextFieldIdVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(jButtonSalvar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelRg)
                        .addComponent(jTextFieldRgVet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTelefone)
                        .addComponent(jTextFieldTelefoneVet, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCpf)
                        .addComponent(jTextFieldCpfVet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelIdade)
                        .addComponent(jTextFieldIdadeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCancelar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmailVet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarVet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 631, 420);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro de Veterinarios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 160, 17);

        setSize(new java.awt.Dimension(673, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
      if(flag == 1){ 
       vet.setNome(jTextFieldNomeVet.getText());
       vet.setRg(jTextFieldRgVet.getText());
       vet.setCpf(jTextFieldCpfVet.getText());
       vet.setTelefone(jTextFieldTelefoneVet.getText());
       vet.setIdade(Integer.parseInt(jTextFieldIdadeVet.getText()));
       vet.setEmail(jTextFieldEmailVet.getText());
       cont.Salvar(vet);
       
       jTextFieldNomeVet.setText("");
       jTextFieldRgVet.setText("");
       jTextFieldCpfVet.setText("");
       jTextFieldTelefoneVet.setText("");
       jTextFieldIdadeVet.setText("");
       jTextFieldEmailVet.setText("");
       
        jTextFieldNomeVet.setEnabled(false);
        jTextFieldRgVet.setEnabled(false);
        jTextFieldCpfVet.setEnabled(false);
        jTextFieldTelefoneVet.setEnabled(false);
        jTextFieldIdadeVet.setEnabled(false);
        jTextFieldEmailVet.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
      }else{
        vet.setCod(Integer.parseInt(jTextFieldIdVeterinario.getText()));
        vet.setNome(jTextFieldNomeVet.getText());
        vet.setRg(jTextFieldRgVet.getText());
        vet.setCpf(jTextFieldCpfVet.getText());
        vet.setTelefone(jTextFieldTelefoneVet.getText());
        vet.setIdade(Integer.parseInt(jTextFieldIdadeVet.getText()));
        vet.setEmail(jTextFieldEmailVet.getText());
        cont.Editar(vet);
        
        jTextFieldIdVeterinario.setText("");
        jTextFieldNomeVet.setText("");
        jTextFieldRgVet.setText("");
        jTextFieldCpfVet.setText("");
        jTextFieldTelefoneVet.setText("");
        jTextFieldIdadeVet.setText("");
        jTextFieldEmailVet.setText("");
        
        jTextFieldNomeVet.setEnabled(false);
        jTextFieldRgVet.setEnabled(false);
        jTextFieldCpfVet.setEnabled(false);
        jTextFieldTelefoneVet.setEnabled(false);
        jTextFieldIdadeVet.setEnabled(false);
        jTextFieldEmailVet.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonCancelar.setEnabled(false);
      }
      
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNomeVet.setEnabled(true);
        jTextFieldRgVet.setEnabled(true);
        jTextFieldCpfVet.setEnabled(true);
        jTextFieldTelefoneVet.setEnabled(true);
        jTextFieldIdadeVet.setEnabled(true);
        jTextFieldEmailVet.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarVetActionPerformed
       vet.setPesquisa(jTextFieldPesquisa.getText());
       Veterinario vetp = cont.pesquisaVeterinario(vet);
       
       jTextFieldIdVeterinario.setText(String.valueOf(vetp.getCod()));
       jTextFieldNomeVet.setText(vetp.getNome());
       jTextFieldRgVet.setText(vetp.getRg());
       jTextFieldCpfVet.setText(vetp.getCpf());
       jTextFieldTelefoneVet.setText(vetp.getTelefone());
       jTextFieldIdadeVet.setText(String.valueOf(vetp.getIdade()));
       jTextFieldEmailVet.setText(vetp.getEmail());
       jButtonEditar.setEnabled(true);
       jButtonExcluir.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarVetActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomeVet.setEnabled(true);
        jTextFieldRgVet.setEnabled(true);
        jTextFieldCpfVet.setEnabled(true);
        jTextFieldTelefoneVet.setEnabled(true);
        jTextFieldIdadeVet.setEnabled(true);
        jTextFieldEmailVet.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldNomeVet.setEnabled(!true);
        jTextFieldRgVet.setEnabled(!true);
        jTextFieldCpfVet.setEnabled(!true);
        jTextFieldTelefoneVet.setEnabled(!true);
        jTextFieldIdadeVet.setEnabled(!true);
        jTextFieldEmailVet.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldIdVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdVeterinarioActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
                vet.setCod(Integer.parseInt(jTextFieldIdVeterinario.getText()));
                cont.Excluir(vet);
                
        jTextFieldNomeVet.setText("");
        jTextFieldRgVet.setText("");
        jTextFieldCpfVet.setText("");
        jTextFieldTelefoneVet.setText("");
        jTextFieldIdadeVet.setText("");
        jTextFieldEmailVet.setText("");
       
        jTextFieldNomeVet.setEnabled(false);
        jTextFieldRgVet.setEnabled(false);
        jTextFieldCpfVet.setEnabled(false);
        jTextFieldTelefoneVet.setEnabled(false);
        jTextFieldIdadeVet.setEnabled(false);
        jTextFieldEmailVet.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID","Nome","Rg","Cpf","Telefone","Idade","Email"};
        conex.conexao();
        conex.executarSql(sql);
        
       try {
        conex.rs.first();
        do{
          dados.add(new Object[]{conex.rs.getInt("id_veterinario"),conex.rs.getString("nome_veterinario"),conex.rs.getString("rg_veterinario"),conex.rs.getString("cpf_veterinario"),conex.rs.getString("telefono_veterinario"),conex.rs.getInt("idade_veterinario"),conex.rs.getString("email_veterinario")});  
        }while(conex.rs.next());
      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "erro ao preencher Arraylist: "+ex.getMessage());
      }
        Tabela tabela = new Tabela(dados, colunas);
        
        jTableVeterinario.setModel((TableModel) tabela);
        jTableVeterinario.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTableVeterinario.getColumnModel().getColumn(0).setResizable(false);
        jTableVeterinario.getColumnModel().getColumn(1).setPreferredWidth(10);
        jTableVeterinario.getColumnModel().getColumn(1).setResizable(false);
        jTableVeterinario.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTableVeterinario.getColumnModel().getColumn(2).setResizable(false);
        jTableVeterinario.setAutoResizeMode(jTableVeterinario.AUTO_RESIZE_OFF);
        jTableVeterinario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
        
        conex.desconecta();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisarVet;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableVeterinario;
    private javax.swing.JTextField jTextFieldCpfVet;
    private javax.swing.JTextField jTextFieldEmailVet;
    private javax.swing.JTextField jTextFieldIdVeterinario;
    private javax.swing.JTextField jTextFieldIdadeVet;
    private javax.swing.JTextField jTextFieldNomeVet;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRgVet;
    private javax.swing.JTextField jTextFieldTelefoneVet;
    // End of variables declaration//GEN-END:variables
}
